[package]
name = "trace_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
pnet = "0.35"
pcap = "2.2"
calamine = "0.26"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
plotters = "0.3"
clap = { version = "4.5", features = ["derive"] }